# Generated by Django 6.0.2 on 2026-03-13 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_exam_user'),
        ('students', '0002_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='session',
            field=models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], default='AM', max_length=2),
        ),
        migrations.AddField(
            model_name='exam',
            name='subject_codes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='exam',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='students.subject'),
        ),
    ]
