# Generated by Django 6.0.2 on 2026-03-13 16:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_semester_student_subject_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='register_no',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('user', 'register_no')},
        ),
    ]
