# Generated by Django 6.0.2 on 2026-03-23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0005_uploadhistory"),
        ("exams", "0003_exam_session_exam_subject_codes_alter_exam_subjects"),
        ("seating", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StorageArtifact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("kind", models.CharField(choices=[("upload_original", "Upload Original"), ("upload_normalized", "Upload Normalized"), ("runtime_input", "Runtime Input"), ("runtime_output", "Runtime Output")], max_length=30)),
                ("b2_key", models.CharField(max_length=512)),
                ("file_name", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("allocation", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="storage_artifacts", to="seating.seatingallocation")),
                ("exam", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="storage_artifacts", to="exams.exam")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="storage_artifacts", to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
