# Generated by Django 4.2.11 on 2026-03-27 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0003_hall_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
