# Generated by Django 4.2.11 on 2026-06-15 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0004_alter_hall_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
